---
lang: pt-BR
title: "Métodos Quantitativos Aplicados à Administração - 2026/2"
subtitle: "Bacharelado em Administração <br> IFMG Campus Formiga"
---

## Bem-vindo à disciplina

Esta disciplina objetiva Aprofundar a formação iniciada na disciplina obrigatória 
[Introdução à Ciência de Dados](https://washingtonsilva.github.io/site_bach_icd2026/){target="_blank"}, capacitando-o a desenvolver análises quantitativas reproduzíveis em ambiente computacional moderno, 
com uso de métodos introdutórios de modelagem estatística e preditiva para apoiar decisões.

Recomenda-se que os alunos matriculados acessem a página 
[Ambiente computacional](ambiente_computacional.qmd) para criar as contas,
instalar e configurar os programas necessários em seus computadores pessoais, 
para não ficarem limitados apenas às atividades no laboratório


## Informações gerais

- **Professor:** [Prof. Dr. Washington Santos da Silva](https://washingtonsilva.github.io){target="_blank"}
- **E-mail:** washington.silva@ifmg.edu.br
- **Horário de aula:** Quinta-Feira (20:30-22:20) e Sexta-Feira (18:40 - 20:20)
- **Local:** Laboratório de Redes (LAR), 1 andar, Bloco B.


## Conteúdo

Use este site como guia da disciplina:

- [Ambiente computacional](ambiente_computacional.qmd): contas, programas e configurações
  necessárias para instalar o ambiente computacional em um computador pessoal.
- [Programa da Disciplina](programa.qmd): objetivos, bibliografia, plano de aulas etc.
- [Cronograma](cronograma.qmd): slides, arquivos de dados.
